#----------------------------------------------------------------------
# This file was generated by encode_bitmaps.py
#
from wx.lib.embeddedimage import PyEmbeddedImage


#----------------------------------------------------------------------
app_sidebar_list = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAGXRFWHRTb2Z0d2FyZQBBZG9i'
    b'ZSBJbWFnZVJlYWR5ccllPAAAAZ5JREFUeNqkU71KA0EQnt3bC57hDIKm8CcJgYAhdhaSwkLw'
    b'GfIKgo1NGp9AbHyAPISQSlJYiYWNlVZCChsFjSRcfm7vbjfO7MVUl0jMwMcue/N9983sLBuP'
    b'x7BMiFqtVsT1EOEuyPUQj0IpVa3X6xfZbLaiVARRpBAhhCHtI9BaQ2zSAsaEgRAp6HQ6L43G'
    b'9aXAhLXBYFBpt9smmYCiBvP2iEqz2UwL27Z1Ya8KCg9/gzMG4L9DqVSaW0Or1WICbbKrh1Xo'
    b'90fQ7fYRHvR6Q7g5syf2k5vM8CfEJQF+fvANvpSTTw6kUhmI5MfUblJwzkmAG4EIE++ePSiv'
    b'd5GkYWNzC1wRTWtOCsuyYoEwDDklHZcdkNKG0VCB9DU4K/EtEJKCSiOuCILAIpu3Tx7s2p+m'
    b'tly+YIgkPEuA8ohLAlz6Co5KaTx0ERw09g3VjQCts3pAXOMgCBjcvwZQdL5QmsP2Tv5PB0KI'
    b'2AEOkU3TdbKfweOMmToZaOyDb2zinMwswXBd1z3Fjub+85DQ4RszFx8/JLEgn2rz2LLP+UeA'
    b'AQCGMhKfzFJvEwAAAABJRU5ErkJggg==')

#----------------------------------------------------------------------
app_sidebar = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAGXRFWHRTb2Z0d2FyZQBBZG9i'
    b'ZSBJbWFnZVJlYWR5ccllPAAAAWJJREFUeNqkUztOw0AUfLveRSTIlC4RQoqE5AOgXCRX4AJu'
    b'OAEdB8gtUuYIOQBtChqqVJGx4/2Yec9xBJITFPKkkVfenXkz+1Ft29IlZWaz2QO+T0B6JncL'
    b'rEwIYVoUxUuWZXkInrwPgCPneOwpxkidyYSUMgJjrmiz2bzP52+vBgtuy7LM1+u1LGZAVHBq'
    b'DOSLxeLGWGvj/eOUAn72pZUiqj9pMpmczLBcLpWBTeVgtWmawwRESe87HdtkhSbMZQEdIOCc'
    b'+zWp8a+3O1RaaxbQIuCxsBcIIVJVOUqNP2QeqiRJOgEQdb9wVwcqS0fj8YhG190pMIaKozHX'
    b'IHvCNmuQq68IaxYRxJ6IHhPgmMxlAc2dm53G+RohK5VIpPAj2tAeMFccNI0C2YoqC2D6Twfc'
    b'TBzgEtnudvXZOuzqWgT5SI9FEG6aps/Y0bv/PCQ4/MCVo9H+IZkz+Zxtqy59zt8CDADZswvP'
    b'7WAwlQAAAABJRU5ErkJggg==')

#----------------------------------------------------------------------
broom_pencil = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAGXRFWHRTb2Z0d2FyZQBBZG9i'
    b'ZSBJbWFnZVJlYWR5ccllPAAAAx9JREFUeNqMk3tI01EUx7/XTS2XZg4z56s12dwmOZ0omo9p'
    b'kjPtQWVCRQXS64+IIEhE6GVg/WFIhSRZUCCRUYSWy4qpLK3U+SgTs0gtxUrTdM05f9vt/mRB'
    b'9AAPfO49nHvO+d1zz/mRZkJ0K4AjRpXqvEGlatm/8Q54GX4N7D1HkaMlyI4BKAWcDFsvhaeQ'
    b'6czHbgfcvgKnpCdObO729l5LKQ3HAoTl0TudaGNJ9W7fKD2bWVFxocRoPGO1WvXMmPqHfwIL'
    b'uMrD9BQ+yGpDcWLWFq1lBsVCB1DfZrONqtXqiR5T3sVH9+seeonmAxsZ4bXtdHXZlZJ8voba'
    b'y4XiHzMIiUtP1VbfuNvOOVAkyMwn7Ix+FvtPC6a/NIbm7ipY19ttCuKsiL7XBN93796XGxqG'
    b'EOr+ERGJ+oiBocb2ppoBy/g0irw8YRBkxxB3qb/DT+brcNo5LOnuMoVs310QOzLaF3Vs36aN'
    b'T1utJD09E4YXnyERDkERq1OMTbR0BEhJk1cgGRBkRZNTi0TLDouWBWwVi2VR/oHKILO5wSNn'
    b'6x6PHvNDslqxAg8aPkGny0Ld8xEEeQ5DptTK+3s6PNhD3nVjy2PL94lZRdz6JIlMGyW0i30E'
    b'k4Hk1rXr0O+sR/9LEzbETKO2thrJydmo6QnE1OAUOA6EAYE+igw2t9PJZmOrUkQhES1dgmCF'
    b'HJzdG7crS3CotA/5OdFQ+lpR9aQTcnk88o6erloTjkrqxAehq1WGmEgyMz5uPh6REJnVb34D'
    b'IRUgIzMbaSlzsIxNwjdsOXarvyPuYB4/aeWsKSbCFAEIwZQFkEnIYOcbOt76rEsZv0YjCVKt'
    b'xEjvILhZDj7BYkz0jaD6/s0mbQhK24ZIQ6gf8GoYIL+mRbqcIIzVkBRJ0hxOFMrlCRlO9kAy'
    b'jQJfWbDB+LiF2U9+s6G+5vV86/89pmFiAp0U+lw12uoubaMVB2LpDg1epq+CPsD7b3/+Bm4M'
    b'fvZ8GLzLYt6mkSBaIcZB/kNvx1DWOQoj//8wZhlzLt1BXEk8GJ6u3d1l4+/odMEmHpxr/x1K'
    b'/lvLAuWnAAMA6WZMRJROxG8AAAAASUVORK5CYII=')

#----------------------------------------------------------------------
edit_size = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAGXRFWHRTb2Z0d2FyZQBBZG9i'
    b'ZSBJbWFnZVJlYWR5ccllPAAAAMlJREFUeNpi/P//PwMlgImBQjDwBrCATWHCMGc6lM7EpfHf'
    b'v384XSAPxL+AWALKRgY6QLweSuM0wAWITwIxK5SNDDqA+D2UhgBQNDIyMiLjRUCsCMS1UDYD'
    b'NgzSB8LoLlAC4t9AzA/Ej4FYFioGA/uBeDmUxuqCXCA+ioZzkeQNoWKGMBcwwFIiVMFmIFZB'
    b'0tAFFUNWg+IFmAGcQLwKiB9CaSkgdofyYWJcyIbADGCEeoETqoAdR7SDwuUrEH9D9jrYwKGf'
    b'mQACDABnjk+ft8DnfwAAAABJRU5ErkJggg==')

#----------------------------------------------------------------------
lock_warning = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAGXRFWHRTb2Z0d2FyZQBBZG9i'
    b'ZSBJbWFnZVJlYWR5ccllPAAAAnNJREFUeNqMU01oE0EU/mYzu0lsIrZWWgIWjNBqVApK8VJM'
    b'heileKsoRShegj3VgwcRD9aDCuJBvOmh6EFsLVivpWKjFpGqqLVRKaSYlpKIMW0Tu/nZzfhm'
    b'041peumDj5n35r3vfW9nloHsUAtDbyfDwRbAoTC4NBxhQJCOmlC2pAAiuQI+mCWBr3Hg8RuB'
    b'mbgAu9mrWIW2KYx1eHf6wvuPnz+5lPjtljFfc6P+7eXQeCa1dL8kxLSdK4n43mZAL6DKxInD'
    b'nX3db1+Mp6Of343JSKD9aKjjWF/365Eb8+RWCGStonEGGxkdErsFczXF5z4uahwDEnIvY/JM'
    b'5nAHg7oOvqNuvS+BMYb5ZMnzd2VVgSjmPTRAahXQ1GJez2SVjC48vgYGr1uOWq7jVdr73Rpa'
    b'1/JCXVlOgysoUtKwYYo9XGEL32dnIM9I6QPK/UK4J4vY5KDDVnC768KjS8U1HYVcDgWdkNeR'
    b'Ts3BqQHbXGW4PRyTTx7eJfKLtQogDAMlXYdBBHkiyBNBjnyYgEodTIJwuqtLNhK8n5oi6Qo4'
    b'5/Q9FJimgWX6Bg4SmVGpOymp042NBMX/vqMjGETtCE4tu2mEH6+s91YmSKSETeCdjkQ2KUin'
    b'dUuBy1bgVZH8IzzMJognKgqc57aoYDEJldkjXH1WUeD55BjDrVDMci5P+K015E9beB6rxwRB'
    b'2mle2ifXwQi9ByEqBNtH7mThD9VjaOEU2toOoP+sF+Ew8LOxHQtqpxWTOXbx7C96B7RvkP/L'
    b'tS5cCexC65lR5rK6BGD0BIQxGmX8abR8W8M9IidXyolR4+u0XZIE8mK9tVe6BZP3l/knwAAd'
    b'mwxKQ2ImiQAAAABJRU5ErkJggg==')

#----------------------------------------------------------------------
paper_clip = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAGXRFWHRTb2Z0d2FyZQBBZG9i'
    b'ZSBJbWFnZVJlYWR5ccllPAAAAjtJREFUeNqkUsuKGkEU7TExRI0SOuADBhRpJUhU8LFQxAco'
    b'CIbQBsGNgSCiEFykl4ILcePOD8gHiAtB0ZVkofgARUbFhQkoiBiSlUQRR4lRc6uZGdR0Vik4'
    b'XVWn7zl1q+69wi6G3W7HEokEZrPZTml8MBhYG42GcbVa3Q6Hwy/r9fpzLpdbnQmr1Sp2PB4v'
    b'gff7fdLr9YbL5TILhNeFQuEt7N+g/6x7YaVSuTyVPrnX61nj8bhwt9t9ms/nBy6X+93lcn2D'
    b'vRAFsP4hpMXdbtcai8WEpVLpBgTh/X6P+OeQETK8paMYUqbT7nQ6pMPhCMNaHwgEKBjEKe90'
    b'OulYRnG73SbNZjMt9vv9VDQaJU55AGaxWBgN8FarRRoMBloMD0VFIhHikkcz4C8DvNlskmq1'
    b'mg7yeDxUMBgkmHiNRkMAzgzwer1OKhQKOghemYJ7E0y8UqkkwAw7NcBrtRoplUpRkNrtdkfg'
    b'3sQFr4dKUTKZjAAz7NJAD+QHn8/HR2uxWIwEOPQGebfWm0wmSiKREGCGIQORSPRQwcdoXiwW'
    b'u+12i+r6I51Ob0Kh0Md8Pv8VGufGaDRaJ5NJic1mj5fLJQax590CLiqdTveOx+NJUqkUlslk'
    b'MOhxOjOtVkvx+XyCw+EwNdrDFV5ks9nXcrn8vUAguE4mk9zZbGZVqVQUnPoKdR5AAOABngKe'
    b'AB4BrpAB/RmPx6JisWiaTqcvN5vNM3i8+Wg0qh4Oh5+o3QG/TrC7w2/QHmiD/xl/BBgAZH6t'
    b'15boJ/oAAAAASUVORK5CYII=')

#----------------------------------------------------------------------
report_pencil = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAGXRFWHRTb2Z0d2FyZQBBZG9i'
    b'ZSBJbWFnZVJlYWR5ccllPAAAAhxJREFUeNpiZC5lZgADRoY+IKnPQBy4yPCfoQjOE1NQYAit'
    b'r0/7TyRgLmHeB8QMIMwINSPt7t27M+/du8cAwqmpqQz3n//AarWiFCcDazHLfiDTCUUioLIy'
    b'8++/f////P2LF4PUMOcz7wdiBhDG6oLE5GSGh89/YneBNCcDez7rASDTEUXCo7Aw5xfQhh+/'
    b'f+PFIDXMmcwHgJghzYwJuwtiExIYHj77hdUFSnJcDJyZrAeXb2VwUHj2HyHhkJ5e8P3Pn/+f'
    b'f/zAi0FqzH1Zzt9jZFx/jJHRgQXmgrllZf1H9u8HuyA8Lo7hydPfWF3Axf6agf+npKBifbLB'
    b'5cZGIbiEeWxsyedfv/6/+/oVJ374YNf/NRs2/P/+/ft/NympvvkMDG5YwyA4OprhyZM/KDb/'
    b'+nyM4f2DiQx21kYMciFzHv298de36927S3AFuoGBFR9//vz/6tMnDHzv3o7/Bzd5/P/+rPL/'
    b'mrkO/1WjmC5zGnIy+GsyYo8F/4gIhqdP/oIlfn8+zvDh0SQGexsjhjXrjjIYO1cx6JR5HQNK'
    b'Wf8/gRQLvLq67Z+AIfwOGNIw/Ojp5f+HtniCbV4NtPnq9R3/QWoY7RhPMgoyQvMgAwMoJKUY'
    b'1BgqGXiAJBIIVGSUWrfwhlRZpcbnLTf+P7/+luETWOILwy0gbAeynoEM4AQ5AIhZsMTa02Rv'
    b'xi3vvzLMXHfg/zk0OVAofwYIMACF0LhPPmZXZgAAAABJRU5ErkJggg==')

#----------------------------------------------------------------------
share = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAGXRFWHRTb2Z0d2FyZQBBZG9i'
    b'ZSBJbWFnZVJlYWR5ccllPAAAAlBJREFUeNqkU01LG1EUPZn3ZhxDQjUEojQpBanaRboSaral'
    b'xY0L6S8QLAj5G27cFN1J3buTblzVXa20ljQbC4JSENNASTFGm0xmMl+v974YsWAXpXPncN8M'
    b'75x77n0zCaUU/udK4JnOKRhYJsxBIgNBb+RfIHBBrHeEN/TUkbRgmeXRB6PlzEQmb6dsS0oJ'
    b'0zRhWRYGa85SSPT8nn/y7WSiVq9x4dcGVQVXZrIXepbjOHBdF57n3eRuu4vORQfOlQNq2Zp8'
    b'NJkn1hw0tW8tw5UHVRl6bZIDQ2LpyRL2X+1j7fkaVKhgD9kWFLWqmCp0C9oiE5hoSoIwYSgD'
    b'xZEiZguzelCKIo5j6MFfz15qByTAxFCGKKQKKKQLyKVzKD0swZY2do53sPllEw2voUXCMOwL'
    b'qFsCbDvwAqy8WMFMYQbVWhVbX7dw2DrU02diFEcI4/BugUELRsLQ1mKKIA40kW9NjogchAhE'
    b'wBv+FOAWouEIqx9XMTY8hvH0OBYeL2A+nsdB7QCNdgP1dh31Xh1CilsChhYw9TmbEk3VRMtt'
    b'4cg5wu73XRTvFVF+WsZ0bhqVswoWtxchLarqwWQBAxEJRHD4I2ERwzC0IxZWQqHarGLvdO/m'
    b'FPzAh+/7wBUcAjlwtINuz+35CZGw9EbVn7QGDW2jsoH19+t6Jgz3l+ujgS63IfCTGFnkAzeY'
    b'yt7PJu2kLQZOBhCmgBySOitf+eefz3+4Z+42TvGBzSYppihe0i9VIpcjekB3od/uJVn/RA7e'
    b'IsQxC5iEkev8LxedJS5/CzAASM0G0JzAR+cAAAAASUVORK5CYII=')

#----------------------------------------------------------------------
table_plus = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAGXRFWHRTb2Z0d2FyZQBBZG9i'
    b'ZSBJbWFnZVJlYWR5ccllPAAAAi9JREFUeNqck8trE1EUxr+ZTjKZ+kB31UwtSUiVRFykRsGF'
    b'KGkEF7qqe5e6FARdtVBc+B+0brTg1pU7dSGIWm2sMebRkDQNTVMSoUWC2qZmHp57kkzTuFB6'
    b'4HK/MzPfub9z517pxtTUNQDHsL+oKZZlHX82PT27H/fE5OQtxTJNyabkyiJg27YzqDAPW8y9'
    b'eef9QuwIhFc2TVMWH4iIBySex/27OkY65rOd510tPMKrmIYhmVxAwquSDb/SpM62eOVxjVas'
    b'WZDovdCWo8lsH4bwKoZh7CGwqtu4GzrKeaJQQHR0lPX7bBYXwmHWb1IpIjgB4e0hABPEVCC5'
    b'ssL9HvB48DGf554PahreptOsRQiPQ2DSx7sEwOmREc6/lEqIBINtGip0PhRiPZ/JQHiYgAv0'
    b'EWRWV5lAU1V8LhZ51UFBk8vtIWgXaLWcFroEp4aHOc+UyzgTCLBO0n483ZlDspGGbul4EnoE'
    b'4ZV7N1EQiMivrSFHFKrbja/URmp5GR6ieVddwNnoGAq/ivwbuwRyP0HQ6+V8iYqEfT7cSdzD'
    b'fP0TBqlIw2wALQvxF1dRCX+bUHaazQGrbw+K6+u8ByKy1MaHSgLeeLvohrEB76XOAuUlXfm+'
    b'uam6XC48Pvmzc8LVv+7WuWoUqZfJ9gm8LEN+TQdKorniriuNWq3uj0Qe/s/l2b5evTl0UR+q'
    b'56t17bk+J2+5KuLAazQO0VD+WeG2+wH9vzEMSIuY+X2fnvz4I8AAYtpfN5Cu7WwAAAAASUVO'
    b'RK5CYII=')

#----------------------------------------------------------------------
ui_check_box = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAGXRFWHRTb2Z0d2FyZQBBZG9i'
    b'ZSBJbWFnZVJlYWR5ccllPAAAAVVJREFUeNrEU7FugzAQPUcFhZRmAoaMXbpEXdv/YM7OxtwJ'
    b'MXXJwhBlyMQ/5CPo3EodKiGxoQwhtEAiQpT6WWUgIWolhp50enf2u3c2nNnxeKQu1qOO1lng'
    b'qg4cxyHG2C0PH7jfXOB/cX/h1w5d120KVFUFeLRt+8kwjHFb9Wq1evM875mH4dkJyrIEDDVN'
    b'G/+INSyOYxqNRmPOG7Z+g91uB2coPvXNZkPL5VLE4IB7UeBwONBsNqP1ek37/V6g7/uU5zlh'
    b'7zeBHorQcT6fUxiGApGbpikEwWkVKIoCLk4wmUwoSRJaLBYCkSuKIk4ADrhnAtvtFi4EBoMB'
    b'WZZFaZoKRI7u2AMH3DOBIAjQLYui6F2WZdJ1nabTqUBJkghr2AMH3NpY/Rb4EOmqqt73+/07'
    b'Hl+3zQHn5vz+H1mWvfI4PhVAEf4x+8MEf/K6rCHwb4/pW4ABAGkv7mEJb7TSAAAAAElFTkSu'
    b'QmCC')

#----------------------------------------------------------------------
upload_cloud = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAGXRFWHRTb2Z0d2FyZQBBZG9i'
    b'ZSBJbWFnZVJlYWR5ccllPAAAA2lpVFh0WE1MOmNvbS5hZG9iZS54bXAAAAAAADw/eHBhY2tl'
    b'dCBiZWdpbj0i77u/IiBpZD0iVzVNME1wQ2VoaUh6cmVTek5UY3prYzlkIj8+IDx4OnhtcG1l'
    b'dGEgeG1sbnM6eD0iYWRvYmU6bnM6bWV0YS8iIHg6eG1wdGs9IkFkb2JlIFhNUCBDb3JlIDUu'
    b'MC1jMDYwIDYxLjEzNDc3NywgMjAxMC8wMi8xMi0xNzozMjowMCAgICAgICAgIj4gPHJkZjpS'
    b'REYgeG1sbnM6cmRmPSJodHRwOi8vd3d3LnczLm9yZy8xOTk5LzAyLzIyLXJkZi1zeW50YXgt'
    b'bnMjIj4gPHJkZjpEZXNjcmlwdGlvbiByZGY6YWJvdXQ9IiIgeG1sbnM6eG1wUmlnaHRzPSJo'
    b'dHRwOi8vbnMuYWRvYmUuY29tL3hhcC8xLjAvcmlnaHRzLyIgeG1sbnM6eG1wTU09Imh0dHA6'
    b'Ly9ucy5hZG9iZS5jb20veGFwLzEuMC9tbS8iIHhtbG5zOnN0UmVmPSJodHRwOi8vbnMuYWRv'
    b'YmUuY29tL3hhcC8xLjAvc1R5cGUvUmVzb3VyY2VSZWYjIiB4bWxuczp4bXA9Imh0dHA6Ly9u'
    b'cy5hZG9iZS5jb20veGFwLzEuMC8iIHhtcFJpZ2h0czpNYXJrZWQ9IkZhbHNlIiB4bXBNTTpE'
    b'b2N1bWVudElEPSJ4bXAuZGlkOjMzMDU2NTAzRDU1RDExRTA5QjRBRjk5NzJEQzkzRjBGIiB4'
    b'bXBNTTpJbnN0YW5jZUlEPSJ4bXAuaWlkOjMzMDU2NTAyRDU1RDExRTA5QjRBRjk5NzJEQzkz'
    b'RjBGIiB4bXA6Q3JlYXRvclRvb2w9IkFkb2JlIFBob3Rvc2hvcCBDUzMgV2luZG93cyI+IDx4'
    b'bXBNTTpEZXJpdmVkRnJvbSBzdFJlZjppbnN0YW5jZUlEPSJ1dWlkOkFDMUYyRTgzMzI0QURG'
    b'MTFBQUI4QzUzOTBEODVCNUIzIiBzdFJlZjpkb2N1bWVudElEPSJ1dWlkOkM5RDM0OTY2NEEz'
    b'Q0REMTFCMDhBQkJCQ0ZGMTcyMTU2Ii8+IDwvcmRmOkRlc2NyaXB0aW9uPiA8L3JkZjpSREY+'
    b'IDwveDp4bXBtZXRhPiA8P3hwYWNrZXQgZW5kPSJyIj8+XkegrgAAAlNJREFUeNrEU89rGlEQ'
    b'nt31RVobV3c1GIkkOcRSkFICPUj9QS4lFA3JpbC5BHroITmlodA/oo23HHvpTXIoNFDSQylK'
    b'Dr2UQgMFN0GrZE3MRsGq+0vdvLGa5tBbDn3w7c58M/O9eftmGdu24SaLhRsux9LSK+A47grD'
    b'JYRCE8uC4E6gU683c5VK7T2aowTsvN/vg+MfokIsdj+TTkelQEAk7bYJ5fL5aj7/LXlw8GPz'
    b'usigg+sOKk5PB1ZSqahE3wQ5p5OAadokFpuX6L7eVkurX1z8ph2dDToaCQhTU/5ln49PTE6K'
    b'EUHgia53r4Q5jgGed5O1tSdp9BVFXd3f/5rM5b5vOuiuQiLxILO4GJU8Hg/RNAsMow8nJwrs'
    b'7n7ew4J0OpnyeLxgWTYwDIDfL5J4fF6S5XLOEQyKKwsLDyWe95BezwaWZemZq7Czk90+Pa1v'
    b'oUCppLxZX3/6guN8VICBXq8PLpeL8Lwrzrrdt+OEjJFmsw26boCqnkMm8277+Liy1el0AIE2'
    b'ctXqGfV1aLc1KtKjN9ETWPoQLcuixToSkM1+3JPlX1h8dySANnIYwxzMRZimyTg0TbfQwdac'
    b'TgfMzATDNPCBtl0oFpXBEWZng8+RR3S7XfqNjMEcYC17dFT6oqqqgaSqNoB+nPDGhpQSxfFw'
    b'rVaERqMBaCOHMcz5k6saWMt4vY/G5+ZCz4LBiTjLMs7R1RUKP/OHh59e49BFIo9fhsP34n/n'
    b'xTYUpZaX5cpbZsiNUdzBucECCoNCozCHPsZvDePsMN7COPPf/8ZLAQYAA4EyGr/gmVQAAAAA'
    b'SUVORK5CYII=')

#----------------------------------------------------------------------
user_gray = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAGXRFWHRTb2Z0d2FyZQBBZG9i'
    b'ZSBJbWFnZVJlYWR5ccllPAAAAnZJREFUeNqUU19oUmEUP9+9V901NdZSUhtOIbe6SzTKIha2'
    b'KNjawM2nqBfpJSjWWM+LGD331FsPewt6C/bQy9igCJGwRZGjaRFRagN3bdP576pf57vTULeX'
    b'DvzuOd/5fud8557vfARQjISAETpETwBuoB5prt9SgBeoiy1CnoFS4G0YrIN9cntIku5OTE9f'
    b'PunxDBcKBdcfWVbQ/75F0DUP5hpoHIBJi80mybmcmM1mxV6zWWK+g7hC4ETn0ZgUVjeo80H4'
    b'onbYbVV9nxMZ7WQk4rwySACr7hBh1E26EyxEM0a71+MEpVRSfczWm0z2UXdhARM8audzLGE7'
    b'GhS4m95KnAXXKhUVzGY+ttfN5+r47cLDYwYlkdvMlCoYyMBs5mN73Xw+maTwDpGWAQ714P1h'
    b'e7HMUrm467ccd1nqtRqsvX6VkDfTT7CCbynkrX4CWP5IIYpxQutfUluYZAt7sLeM3FJiO1Q0'
    b'q4v4h9jO8xUagbbS/zVx/wjAIOJsr+v8gNfnUx3p3/IArESDaMYQGx1NZ7fITuUA7KgvoGl9'
    b'trT0dOvXF7h0ildJb9Zr0GcfgjvB4AwuM1hBFGcgxSrh+/YSnLE6HOHA+PjEvfn5+4IgQLnO'
    b'Q7J6FL7vHgYNzp0oinB1auo6r9GY8vl8f357O8eSCc1/GgvPzs6Ier2hWCyqZEVRIBQKqRW8'
    b'XFxUNds7FwiMnfb7Rx7PzRXQtSZ8xcY7CHFqtFoDbRuzarUKOMaNps21/IzDuArG/KCUPTrw'
    b'HSHkmoiN4whRkFlGXSaEVI2StK6+vHhcwkBtg1IdZuxBW4PPMiZTuswSaBD9Tf0/wl7nz78C'
    b'DAAL1yLBhlZuAQAAAABJRU5ErkJggg==')

#----------------------------------------------------------------------
user = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAGXRFWHRTb2Z0d2FyZQBBZG9i'
    b'ZSBJbWFnZVJlYWR5ccllPAAAAopJREFUeNqUU19IU2EUP/fP7t1m2xCZOc1yZk6asy0qy4mm'
    b'glAtCEkSM+gtiqDopZf+YG9Rz0HvBVbQS7AHH/qjYZraKvJBHYr0MATZyrbd3Xu993bOdYs5'
    b'9tKB33fO9zt/vvPd71zGwTBAIiIE+Cd2ZIdQd+b3Hw2AMdRZ2igIOe/gHVBWLvn8/ivt4XCL'
    b'oqowPTkZXI3HLcg/hfxBhcNYHZcyiFTX1vqTqZRtY2PDVul2+4krF8t3H9h5NN3o7aLhvXW5'
    b'Q2ht9pjcj6WEEJma8vb6GDCMnfF8TzNTWmB0OuGoC7Z5QZUkkyPb7nTW9TSnR7HA/eJ4lgoW'
    b'QzeAHQ7KC5S8JcsmyCaOfKXxrIZrCe7W7FKXUusJScZEAtnEka80nr/heo19s9CkL0J/5jk0'
    b'Kt+os7H599Fjh7vP+Gnz5UN0RdONMQ3tFeEQjFdchDjrwxZ04At3iVsCEK98BMARxcw+iPVs'
    b'Gja36VuIzW3e2/du1mxa20KFpTRl+yOWmYEjGNEvtJxuCIaCJrGcZBpAMq6iOY6YKw7m2MDQ'
    b'9tux3H7Uw9hW15PrnXdy1j2O4zW/QbTZYN55zjFwKtwXnVlNYw4+vJHELlLUUb4AdO12WW+G'
    b'D1b3XYu0DvI8D+tZAaR0GlYzLlgTA+ByVUBvwHOCAa0qnZH8mZySxGJrPGjmVA+OnGwbtImC'
    b'PZtVwWoVQcURHjg/YLb5+dWKqbNZBY42VrUH6p2Bxy9n/iA1wWovLtgh92uvhWPsRtGYKYoC'
    b'OMY6geyCUIyFZcwcyqUxDHHBkbPgCXUBa1EMTswhJOAEuW354SdK+t50uwN0RWQ02UoAXRUg'
    b'EZvQvj57QwXoL6vP6/8RFfHzrwADAL82JG8NF+QSAAAAAElFTkSuQmCC')

#----------------------------------------------------------------------
user_medium = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAGXRFWHRTb2Z0d2FyZQBBZG9i'
    b'ZSBJbWFnZVJlYWR5ccllPAAAAflJREFUeNpi/P//PwMlgImBQsACIqSZUM1hZGAQB1J5QKwA'
    b'xA+AeBLQnS+R1Tz99w9hALongPxyQzOzCF19feELZ8++vXTuHCdQuAinC+zVGFEE99/6b9mQ'
    b'7ympoybJcOWWlKRv9DlLRzQ1KAY4qqGIhZ96wadqoKvA8PvHDwYQzc3Hp+qo9jkcKLcSqwF/'
    b'/qEGbLj+z5s/Pn+2+vP7N8NfIAbxgWqYcLpgGzvQcEYmBpW/VxlUfl1aLsH90/DNsydGHFw8'
    b'HD++ffkB5B/9959x+R02PYY7zNrAQPrHkIVswA4OoAFMzAwMzOxAzMrg8mnRMublsx1ldSxN'
    b'Hl85fmUbd8KyPXxxDEDnAPFPBoZ/f/Glg/8mQMXeb96+YzQyMWUA0SA+SBynF6BAAOi0CC7m'
    b'f1oZvrpBXB/3Sh///paBK3mvcbGAtsT0TZfEv/35BzJkBRB/QHUB0E9A5yX7GkuklwXrpimK'
    b'80q/41BkCAoKYgDRIH5FqH6an4lkOkgdWD2yAf8vLWVg+PnJRE9ByODfn3/sILEfwCh8+/Yt'
    b'mAYBkDhIHqQOrB6WakGZiZGRUZ3ZIDaMQdLQ/j8z+/f/LJxfGFg4v1m/mHryiES2OeOfH1yM'
    b'f75zM/79ycnw/NyhvxcWrwLqu4lsAIitTkIeugnLxYyUZmeAAAMATarQH7iCU4EAAAAASUVO'
    b'RK5CYII=')

#----------------------------------------------------------------------
folder_plus = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAGXRFWHRTb2Z0d2FyZQBBZG9i'
    b'ZSBJbWFnZVJlYWR5ccllPAAAAe9JREFUeNqMUz1IW1EYPe9PTMyggcQqCFboUKGohC510Qx1'
    b'KQhOgiC4VHAQpJODQunSUboEJy3FoUMHB0VFsXvqUGgxKkrAYkFUtH0NL+/dn373PeOrTUy8'
    b'8PHd93POPee872nZt/CXBoxRa8f9Vl4CC2pjShncofbw6eTyDDivDjUMZN8Nvild3hDQ0sE8'
    b'SM+ritcsC4TRbwi4CAkEnS5rKNB0HYQJCUSowJD3IAAREMaoqECBBWc18P8p+IfAENwDZ7Uy'
    b'MBWBoVKXZQSMFLC7FViRKH7kDgICIEVh7uiK4LooA+ZbqFQ6fb7jvQN/n34tJun9MZWf+aEx'
    b'ggbi22uw+qe/Z9BV34y5ludlpwvy/vvyEo+ePEbBdUsqYC7FI6ijSOJSJl/0DiC7vQqeYBXC'
    b'M2jGAou244DcGsHwSMy7Al/gSu2KXwEuR3r3Pabya1ChhsXAWGDnT7HoK1DWTRRFqn8onVJs'
    b'Z+wM8b5O/8Sv698gWsOZUJ+YX8/Jy3wCEyULcMTO9tImmj3RkRjpadJXf/qArljy1lBJweGQ'
    b'dNXPzwtwXNTnThTBq19T9DwmZ6P7F/wCyaLE1rPR8gw0HbZt+338U2xl6xAfFz8jSn8x4lSt'
    b'TYNmxnqgdbdJaQ8XWK7aMB2d4jCzgTnanvwVYADmgBJMMBgTjAAAAABJRU5ErkJggg==')

#----------------------------------------------------------------------
bin_full = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAGXRFWHRTb2Z0d2FyZQBBZG9i'
    b'ZSBJbWFnZVJlYWR5ccllPAAAAvRJREFUeNp0U0tME1EUfTOdfqcz05YWWhSKFjSWjwsESS0b'
    b'qTER2UBwadyYmLBzUxeu1JUL4kITY2LiwuiCDZEQEVI0pBEWxE+ExFSqRWmhnVL6nenQN1Pf'
    b'qy2CwZec9z3n5N6Xe4nR0VGAhyRJIBQKgXA4DKAsA/fISCu6Po8wvzk/v8YyDDCbzcBkMgEG'
    b'7VUqVUVHgb9jCMGBNyRF6cOzs/ZBn88zEwic1anVGXSdRShWEUGYrBiEjw3UDNg3T1+Orawn'
    b'srKUYy70uJsESc7ISrl5bnk1wbGWkkFvgM1W2nxl/Pn9mogsl8ugCiIvFFR8Kqn1dJ60Vh4J'
    b'glSrSO1Ad7ud30lqCoJQiRhza7r9BuRWMkn5utvrMUksSmAtGhP9D/OOaLzMXTzTYedTvKZq'
    b'sKej8FQdREOdFc4tf0l43B2uFzMFNsYbLHpdCT6agNywLxm1Way7iKfFERyWAsnQtNxotRKT'
    b'b9Paa5dNxfGblvhOBlKD/WJMBqo8baDhvxGQiqKAKohcPk8VhLzG02WQk+n1DGZcHxa+drUx'
    b'u7kMdVQFoBEbYG5NdyCCGB+net1tnNtFFyCsM1+9/d3e1mTnRFFtjPP6us3EljpXyFH/i4B0'
    b'2OrhzNKnBEkA8t6TqIGjy8qNO+uOZ5MJ06V+Nn/u9CkulohTmFvT4cPef7BGBjIICx9X+btj'
    b'rdytB990E+Od8WJJLpWgIk+//8D3ul0GbHDoJ2ayWSqVTqnbjzexYvFnEolju1CRUDHBqeAy'
    b'b7c1SAzNwAMpFDbW9lKIbPyihrw9NhPDqFqONGqnFpY2EElBa9JRb5cYIwurn1hJAWup6KvH'
    b'wOv1ApqmJXHLeeJ16HPFUBAEsL29bVt5Nw10Ol1LzmgEHMcBnmWB60dAzmazYHFxsdJM+mAw'
    b'yDidTk1fXx9Ip9NAFEUAoQJ4Po+6tIwM9IBFQmyAu9Hv91ORSARXbA5XlAWhEbXnAArXVssN'
    b'V2ZlIv4U3b4VP/KyLAfQGvstwABqINJ/FPbnWgAAAABJRU5ErkJggg==')

